[project]
name = "pomo25"
version = "0.1.4"
description = "A CLI pomodoro timer that logs sessions to a JSONL file"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "nava",
    "python-dotenv",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
pomo25 = "main:main"

[tool.hatch.build.targets.wheel]
include = [
  "/main.py",
  "/pomo.py",
  "/assets/break.wav",
  "/assets/end.wav",
]

[dependency-groups]
dev = [
    "ruff>=0.16.2",
]
